// Unicode box-drawing connectivity: left, right, up, down; 1 light, 2 heavy.
// Generated from Unicode character names, independent of installed fonts.
pub(super) fn arms(ch: char) -> Option<[u8; 4]> {
    match ch {
        '─' => Some([1, 1, 0, 0]), // LIGHT HORIZONTAL
        '━' => Some([2, 2, 0, 0]), // HEAVY HORIZONTAL
        '│' => Some([0, 0, 1, 1]), // LIGHT VERTICAL
        '┃' => Some([0, 0, 2, 2]), // HEAVY VERTICAL
        '┌' => Some([0, 1, 0, 1]), // LIGHT DOWN AND RIGHT
        '┍' => Some([0, 2, 0, 1]), // DOWN LIGHT AND RIGHT HEAVY
        '┎' => Some([0, 1, 0, 2]), // DOWN HEAVY AND RIGHT LIGHT
        '┏' => Some([0, 2, 0, 2]), // HEAVY DOWN AND RIGHT
        '┐' => Some([1, 0, 0, 1]), // LIGHT DOWN AND LEFT
        '┑' => Some([2, 0, 0, 1]), // DOWN LIGHT AND LEFT HEAVY
        '┒' => Some([1, 0, 0, 2]), // DOWN HEAVY AND LEFT LIGHT
        '┓' => Some([2, 0, 0, 2]), // HEAVY DOWN AND LEFT
        '└' => Some([0, 1, 1, 0]), // LIGHT UP AND RIGHT
        '┕' => Some([0, 2, 1, 0]), // UP LIGHT AND RIGHT HEAVY
        '┖' => Some([0, 1, 2, 0]), // UP HEAVY AND RIGHT LIGHT
        '┗' => Some([0, 2, 2, 0]), // HEAVY UP AND RIGHT
        '┘' => Some([1, 0, 1, 0]), // LIGHT UP AND LEFT
        '┙' => Some([2, 0, 1, 0]), // UP LIGHT AND LEFT HEAVY
        '┚' => Some([1, 0, 2, 0]), // UP HEAVY AND LEFT LIGHT
        '┛' => Some([2, 0, 2, 0]), // HEAVY UP AND LEFT
        '├' => Some([0, 1, 1, 1]), // LIGHT VERTICAL AND RIGHT
        '┝' => Some([0, 2, 1, 1]), // VERTICAL LIGHT AND RIGHT HEAVY
        '┞' => Some([0, 1, 2, 1]), // UP HEAVY AND RIGHT DOWN LIGHT
        '┟' => Some([0, 1, 1, 2]), // DOWN HEAVY AND RIGHT UP LIGHT
        '┠' => Some([0, 1, 2, 2]), // VERTICAL HEAVY AND RIGHT LIGHT
        '┡' => Some([0, 2, 2, 1]), // DOWN LIGHT AND RIGHT UP HEAVY
        '┢' => Some([0, 2, 1, 2]), // UP LIGHT AND RIGHT DOWN HEAVY
        '┣' => Some([0, 2, 2, 2]), // HEAVY VERTICAL AND RIGHT
        '┤' => Some([1, 0, 1, 1]), // LIGHT VERTICAL AND LEFT
        '┥' => Some([2, 0, 1, 1]), // VERTICAL LIGHT AND LEFT HEAVY
        '┦' => Some([1, 0, 2, 1]), // UP HEAVY AND LEFT DOWN LIGHT
        '┧' => Some([1, 0, 1, 2]), // DOWN HEAVY AND LEFT UP LIGHT
        '┨' => Some([1, 0, 2, 2]), // VERTICAL HEAVY AND LEFT LIGHT
        '┩' => Some([2, 0, 2, 1]), // DOWN LIGHT AND LEFT UP HEAVY
        '┪' => Some([2, 0, 1, 2]), // UP LIGHT AND LEFT DOWN HEAVY
        '┫' => Some([2, 0, 2, 2]), // HEAVY VERTICAL AND LEFT
        '┬' => Some([1, 1, 0, 1]), // LIGHT DOWN AND HORIZONTAL
        '┭' => Some([2, 1, 0, 1]), // LEFT HEAVY AND RIGHT DOWN LIGHT
        '┮' => Some([1, 2, 0, 1]), // RIGHT HEAVY AND LEFT DOWN LIGHT
        '┯' => Some([2, 2, 0, 1]), // DOWN LIGHT AND HORIZONTAL HEAVY
        '┰' => Some([1, 1, 0, 2]), // DOWN HEAVY AND HORIZONTAL LIGHT
        '┱' => Some([2, 1, 0, 2]), // RIGHT LIGHT AND LEFT DOWN HEAVY
        '┲' => Some([1, 2, 0, 2]), // LEFT LIGHT AND RIGHT DOWN HEAVY
        '┳' => Some([2, 2, 0, 2]), // HEAVY DOWN AND HORIZONTAL
        '┴' => Some([1, 1, 1, 0]), // LIGHT UP AND HORIZONTAL
        '┵' => Some([2, 1, 1, 0]), // LEFT HEAVY AND RIGHT UP LIGHT
        '┶' => Some([1, 2, 1, 0]), // RIGHT HEAVY AND LEFT UP LIGHT
        '┷' => Some([2, 2, 1, 0]), // UP LIGHT AND HORIZONTAL HEAVY
        '┸' => Some([1, 1, 2, 0]), // UP HEAVY AND HORIZONTAL LIGHT
        '┹' => Some([2, 1, 2, 0]), // RIGHT LIGHT AND LEFT UP HEAVY
        '┺' => Some([1, 2, 2, 0]), // LEFT LIGHT AND RIGHT UP HEAVY
        '┻' => Some([2, 2, 2, 0]), // HEAVY UP AND HORIZONTAL
        '┼' => Some([1, 1, 1, 1]), // LIGHT VERTICAL AND HORIZONTAL
        '┽' => Some([2, 1, 1, 1]), // LEFT HEAVY AND RIGHT VERTICAL LIGHT
        '┾' => Some([1, 2, 1, 1]), // RIGHT HEAVY AND LEFT VERTICAL LIGHT
        '┿' => Some([2, 2, 1, 1]), // VERTICAL LIGHT AND HORIZONTAL HEAVY
        '╀' => Some([1, 1, 2, 1]), // UP HEAVY AND DOWN HORIZONTAL LIGHT
        '╁' => Some([1, 1, 1, 2]), // DOWN HEAVY AND UP HORIZONTAL LIGHT
        '╂' => Some([1, 1, 2, 2]), // VERTICAL HEAVY AND HORIZONTAL LIGHT
        '╃' => Some([2, 1, 2, 1]), // LEFT UP HEAVY AND RIGHT DOWN LIGHT
        '╄' => Some([1, 2, 2, 1]), // RIGHT UP HEAVY AND LEFT DOWN LIGHT
        '╅' => Some([2, 1, 1, 2]), // LEFT DOWN HEAVY AND RIGHT UP LIGHT
        '╆' => Some([1, 2, 1, 2]), // RIGHT DOWN HEAVY AND LEFT UP LIGHT
        '╇' => Some([2, 2, 2, 1]), // DOWN LIGHT AND UP HORIZONTAL HEAVY
        '╈' => Some([2, 2, 1, 2]), // UP LIGHT AND DOWN HORIZONTAL HEAVY
        '╉' => Some([2, 1, 2, 2]), // RIGHT LIGHT AND LEFT VERTICAL HEAVY
        '╊' => Some([1, 2, 2, 2]), // LEFT LIGHT AND RIGHT VERTICAL HEAVY
        '╋' => Some([2, 2, 2, 2]), // HEAVY VERTICAL AND HORIZONTAL
        '╴' => Some([1, 0, 0, 0]), // LIGHT LEFT
        '╵' => Some([0, 0, 1, 0]), // LIGHT UP
        '╶' => Some([0, 1, 0, 0]), // LIGHT RIGHT
        '╷' => Some([0, 0, 0, 1]), // LIGHT DOWN
        '╸' => Some([2, 0, 0, 0]), // HEAVY LEFT
        '╹' => Some([0, 0, 2, 0]), // HEAVY UP
        '╺' => Some([0, 2, 0, 0]), // HEAVY RIGHT
        '╻' => Some([0, 0, 0, 2]), // HEAVY DOWN
        '╼' => Some([1, 2, 0, 0]), // LIGHT LEFT AND HEAVY RIGHT
        '╽' => Some([0, 0, 1, 2]), // LIGHT UP AND HEAVY DOWN
        '╾' => Some([2, 1, 0, 0]), // HEAVY LEFT AND LIGHT RIGHT
        '╿' => Some([0, 0, 2, 1]), // HEAVY UP AND LIGHT DOWN
        _ => None,
    }
}
