//! Golden results generated by executing the pinned upstream TypeScript.
use crate::{
    appearance::Palette,
    input::{encode_key, encode_paste},
    terminal_render::build_row,
};
use alacritty_terminal::{
    term::{
        TermMode,
        cell::{Cell, Flags},
        color::Colors,
    },
    vte::ansi::{Color, NamedColor, Rgb},
};
use gpui_kit::{Keystroke, component::ThemeMode};
use serde::Deserialize;

#[derive(Deserialize)]
struct Fixtures {
    version: String,
    ansi: Vec<u32>,
    keys: Vec<KeyCase>,
    paste: Vec<PasteCase>,
    colors: Vec<ColorCase>,
}
#[derive(Deserialize, Debug)]
struct KeyCase {
    key: String,
    app_cursor: bool,
    bytes: Option<String>,
}
#[derive(Deserialize, Debug)]
struct PasteCase {
    text: String,
    bracketed: bool,
    bytes: String,
}
#[derive(Deserialize, Debug)]
struct ColorCase {
    name: String,
    mode: u32,
    value: u32,
    bold: bool,
    faint: bool,
    inverse: bool,
    foreground: u32,
    background: u32,
    rgb: u32,
    alpha: u8,
}
fn fixtures() -> Fixtures {
    let fixture: Fixtures =
        serde_json::from_str(include_str!("../tests/fixtures/xterm-6.json")).unwrap();
    assert_eq!(fixture.version, "6.0.0");
    fixture
}

#[test]
fn keys_and_paste_match_upstream_xterm() {
    let fixture = fixtures();
    for case in fixture.keys {
        let key = Keystroke::parse(&case.key).unwrap();
        let mode = if case.app_cursor {
            TermMode::APP_CURSOR
        } else {
            TermMode::empty()
        };
        assert_eq!(
            encode_key(&key, mode),
            case.bytes.as_ref().map(|s| s.as_bytes().to_vec()),
            "{case:?}"
        );
    }
    for case in fixture.paste {
        let mode = if case.bracketed {
            TermMode::BRACKETED_PASTE
        } else {
            TermMode::empty()
        };
        assert_eq!(
            encode_paste(&case.text, mode),
            case.bytes.as_bytes(),
            "{case:?}"
        );
    }
}

#[test]
fn indexed_colours_match_upstream_palette_for_rendering_and_queries() {
    let fixture = fixtures();
    assert_eq!(fixture.ansi.len(), 256);
    let mut palette = Palette::new(ThemeMode::Dark);
    palette.ansi.copy_from_slice(&fixture.ansi[..16]);
    let theme = palette.terminal_theme();
    let colors = Colors::default();
    for (index, expected) in fixture.ansi.into_iter().enumerate() {
        assert_eq!(
            crate::terminal_render::resolve_color(Color::Indexed(index as u8), palette, &colors),
            expected,
            "render palette index {index}",
        );
        let rgb = theme.rgb(index);
        assert_eq!(
            ((rgb.r as u32) << 16) | ((rgb.g as u32) << 8) | rgb.b as u32,
            expected,
            "query palette index {index}",
        );
    }
}

#[test]
fn colours_match_upstream_webgl_resolver() {
    let fixture = fixtures();
    for case in fixture.colors {
        let mut palette = Palette::new(ThemeMode::Dark);
        palette.text = case.foreground;
        palette.terminal = case.background;
        palette.ansi.copy_from_slice(&fixture.ansi[..16]);
        let fg = match case.mode {
            0 => Color::Named(NamedColor::Foreground),
            0x3000000 => Color::Spec(Rgb {
                r: (case.value >> 16) as u8,
                g: (case.value >> 8) as u8,
                b: case.value as u8,
            }),
            _ => Color::Indexed(case.value as u8),
        };
        let mut flags = Flags::empty();
        flags.set(Flags::BOLD, case.bold);
        flags.set(Flags::DIM, case.faint);
        flags.set(Flags::INVERSE, case.inverse);
        let plan = build_row(
            &[Cell {
                c: 'X',
                fg,
                flags,
                ..Cell::default()
            }],
            palette,
            &Colors::default(),
        );
        let run = &plan.text[0];
        assert_eq!(run.fg, case.rgb, "{}: {case:?}", case.name);
        let ink = crate::terminal_decorations::ink(run.fg, run.flags.contains(Flags::DIM));
        assert_eq!((ink.a * 255.).round() as u8, case.alpha, "{case:?}");
    }
}
